do_test : False
dataset_path : "/home/sandhu/project/sens_test/SemanticKITTI_00"
epochs: 30
train_batch_size : 4
lookahead: 30
ckpt_path : None
voxelization:
  point_cloud_range : [-50, -50, -1, 50, 50, 3]
  voxel_size : [0.2, 0.2, 0.3]
  max_points_in_voxel : 5
  max_voxel_num : 150000
